### ISSUE TITLE
Wunschliste

### ISSUE THREAD

**Issue by olien** [olien/REX5-Modulsammlung#11]
Habt Ihr bestimmte Standard Module die ich evtl. hier berücksichtigen könnte?

**Comment by skerbis** [comment]
Wow! Coole Sache das. 
Wenn ich mehr Zeit habe, werde ich mich mit einklinken.  
Als erstes schlage ich vor: 

* [rss! list] (http://www.redaxo.org/de/download/module/?modul_id=644&searchtxt=klxm&cat_id=-1)

**Comment by olien** [comment]
Hi, 

danke. Ich dachet erste einmal an alle MOdule die Nötig sind um irgendeine 08/15 Seite zu befüllen.
Danach kommt die Kür :-))

LG
Oliver

**Comment by skerbis** [comment]
* Artikelliste 
* Kategorieliste 
* Headline
* Kontakt-Formular
* Bildergalerie

**Comment by olien** [comment]
Danke. 

benutzt du Artikel- und Kategorielisten in deinen Projekten??

* Headline ist im ersten Modul.
* Kontaktformular / Text folgt.
* für Google Maps wollte ich den Routenplaner einbauen: http://www.redaxo.org/de/download/module/?modul_id=569

**Comment by skerbis** [comment]
Vielleicht lassen sich Dein Routenplaner und mein irgendwie Modul vereinen? 
Schau es Dir an. 
Als Modulausgabe entsteht nur das: 
```
        <div class="maphide map_canvas">
            <div class="infotext">
                <div class="location">TREDER ARCHITEKTEN </div>
                <div class="address">Schillerstraße 25</div>
                <div class="city">Gladbeck</div>
                <div class="statem"></div>
                <div class="zip">45964</div>
                <div class="country">DE</div>
                <div class="phone">02043 681453</div>
                <div class="zoom">16</div>
<div class="maptype">ROADMAP</div>
            </div>
   
```

**Comment by olien** [comment]
OK. Gucke ich mir an. Danke!

**Comment by skerbis** [comment]
Kleiner Tipp für den Link zur Karte (in deinem Modul) 
Versuchs mal mit
http://maps.apple.com/?q=Dinslaken+Alleestr.%202+DE+46535

Das öffnet auf dem Mac und IOS die Karten-App und bei anderen (Windows / Android / Linux) Google Maps.

**Comment by olien** [comment]
Cool. Danke!

**Comment by skerbis** [comment]
Ja Artikel- und Kategorielisten nutze ich häufig in meinen Projekten. Allerdings etwas aufwendiger.

**Comment by olien** [comment]
Hey Thomas,

hast du mal Lust dir das Google Maps Modul anzusehen?

LG
Oliver

**Comment by skerbis** [comment]
Klaro

**Comment by skerbis** [comment]
Sieht gut aus. Schönes Modul. Aber wozu brauchst Du REX_Markup und Textile? 
Eins von beiden (oder lieber keins von beiden) würde reichen.

**Comment by olien** [comment]
MarkItUp funktioniert halt ohne Textile nicht :-))
Das ist für die Beschreibung neben dem Eingabefeld der Adresse. Stört ja nicht :-)

**Comment by skerbis** [comment]
Hmm…. 
schade, da es kein Core-Addon ist. 
Schlage vor, dass Du dazu einen Hinweis in der Beschreibung hinterlegst.

**Comment by olien** [comment]
Danke. Ich schreibe den Hinweis. (wobei auch auf Redactor geprüft wird. Einer der beiden Edioren wird doch sicherlich benutzt - oder?)

**Comment by skerbis** [comment]
Wenn man Redaxo gerade frisch installiert hat, sind diese Addons ja erstmal nicht aktiv. Daher würde ich es beschreiben. Redactor wird in dem Modul doch garnicht benutzt? Oder? … Redaktor ist bei mir an, er hat aber das fehlende Markup bemängelt.

**Comment by skerbis** [comment]
Ach, 

wenn markitup nicht installiert ist, lande ich im Safe-Mode: 

"ErrorException" thrown in rex://module/9/input on line 10
Fatal error: Class 'rex_markitup' not found


activate safe mode <http://2015.grund-gruppe.de/redaxo/index.php?page=packages&safemode=1>

Hier liegt das Problem

if (!rex_markitup::profileExists('supersimple')) {
    rex_markitup::insertProfile('supersimple', 'Google Maps Modul Profil', 'bold,italic,underline');
  }

**Comment by olien** [comment]
Komisch. Danke

**Comment by olien** [comment]
Besteht der Fehler immer noch?

**Comment by skerbis** [comment]
sorry, war weg. Der Fehler tritt nicht mehr auf

**Comment by olien** [comment]
Gut. Danke
