### ISSUE TITLE
Installation nicht möglich

### ISSUE THREAD

**Issue by skerbis** [olien/REX5-Modulsammlung#12]
Installer meldet: 

![bildschirmfoto 2015-12-10 um 13 05 30](https://cloud.githubusercontent.com/assets/791247/11715027/d1c312f2-9f3e-11e5-8c40-8c5bc151060e.png)

**Comment by olien** [comment]
Ja. Das kommt immer mal wieder. Keine Ahung an was das liegt. Ich verlinke direkt hier auf das GitHub zip. Wenn es gar nicht geht einfach hier das ZIP laden und in den Addons Ordner packen :-))

**Comment by staabm** [comment]
irgendwelche Fehler oder Warnings im php error log?

**Comment by olien** [comment]
Leider nein.

**Comment by skerbis** [comment]
Kann ich bestätigen, sehe nichts in den Logs

**Comment by olien** [comment]
PAL
