### ISSUE TITLE
Illegal operation "deactivate" for package "iconpicker"

### ISSUE THREAD

**Issue by aeberhard** [olien/REX5-Modulsammlung#49]
Wenn das Addon aktiviert ist erscheint die Fehlermeldung in rot
bei allen versuchen ein Addon oder ein Plugin zu deaktivieren.
Das deaktivieren klappt aber
Es sollte eigentlich die Medung **_AddOn xxxx wurde deaktiviert!_** erscheinen

REDAXO 5.1
Modulsammlung 4.3.2

**Comment by olien** [comment]
Hm. Hab keine Probleme. Kann ich das irgendwo sehen?

**Comment by aeberhard** [comment]
Leider nur bei mir lokal auf Windows.

Ich denke mal das hier evtl. der Compiler angeworfen wird was er nicht tun sollte!?

**Comment by olien** [comment]
Hm. Hat noch keiner solch einen Fehler gemeldet... Wüsste grad nicht wo ich suchen soll..

**Comment by aeberhard** [comment]
Hm, probiere hier gerade rum, komischerweise passiert es nicht bei deaktivierter Modulsammlung,
und irgendwie hängt das evtl. auch mit yform zusammen ... werde versuchen das rauszufinden

**Comment by olien** [comment]
Hi Andi, 

ist der Fehler nochmal aufgetaucht?

LG
Oliver

**Comment by aeberhard** [comment]
Bei mir lokal tritt das noch auf, aber soweit ich mich erinnere war das wg. irgendeinem Ajax-timeout ...
Close!
