### ISSUE TITLE
Bildunterschriften

### ISSUE THREAD

**Issue by skerbis** [olien/REX5-Modulsammlung#6]
Kannst Du die Bildunterschriften anders als mit einem p-tag definieren, wie wäre es mit?
```
<figure class="image">
  <img src="irgendwas.jpg" width="xy" height="xy" alt="Irgendwas" />
  <figcaption class="caption">Irgendwas</figcaption>
</figure>
```

**Comment by olien** [comment]
Hi,

width & height würde ich nur angeben sofern bei *Bild anpassen = nein* ausgewählt wurde. -> ok?

Wäre das dann so ok? Ich habe mich mit _figure_ noch nicht beschäftigt.
Was machen die unterschiedlichen Browser damit?

```
<figure class="image">
  <img src="irgendwas.jpg" width="xy" height="xy" alt="Irgendwas" />
  <figcaption class="titel">Irgendwas</figcaption>
  <figcaption class='beschreibung">Irgendwas</figcaption>
  <figcaption class='copyright">Irgendwas</figcaption>
</figure> 
```

**Comment by skerbis** [comment]
Hi, es ist nur ein figcaption je figure erlaubt. figure wird vom IE ab Version 9 unterstützt. Für ältere gibt es entsprechende Lösungen. http://www.w3schools.com/tags/tag_figure.asp

**Comment by olien** [comment]
Gucke ich mir an. Wäre aber sehr schnell selbst anpassbar denke ich.
( Ich passe das Modul eh fast immer für jedes Projekt an :-)

**Comment by skerbis** [comment]
Erstmal vielen Dank für die tolle Arbeit, welchen Zweck erfüllen das CSS und das Javascript?

**Comment by olien** [comment]
Das sind Beispiele damit im Frontend das Accordion funktioniert.

**Comment by skerbis** [comment]
Für die FAQ?

**Comment by skerbis** [comment]
Sag mal, weißt du ob das ausgewählte Bild noch als Vorschau angezeigt werden kann? preview=1 hat bei mir keinen Effekt mehr.

**Comment by olien** [comment]
Ja. Für die FAQ (könnte eine bessere Bezeichnung brauchen)

preview hab ich nie benutzt..
Wann soll wo ein Bild gezeigt werden?

**Comment by skerbis** [comment]
Wir kennen ja unsere Redakteure ;-) Es wäre schön wenn das ausgewählte Bild z.B. rechts neben dem Formular dargestellt wird. Das Formular müsste dann 3 spaltzig werden. 
![1](https://cloud.githubusercontent.com/assets/791247/11444354/eddd6fa6-9524-11e5-96ac-60783005812d.jpg)

**Comment by skerbis** [comment]
Dafür hatte ich mir mal irgendwo folgendes Skript geborgt
```
<script type="text/javascript">
function addEvent( obj, type, fn )
{
   if (obj.addEventListener) {
      obj.addEventListener( type, fn, false );
   } else if (obj.attachEvent) {
      obj["e"+type+fn] = fn;
      obj[type+fn] = function() { obj["e"+type+fn]( window.event ); }
      obj.attachEvent( "on"+type, obj[type+fn] );
   }
}
function rex_media_preview(){
  var strFileName = document.getElementById("REX_MEDIA_1").value;
  if ( (strFileName.lastIndexOf(".jpg")>0) || (strFileName.lastIndexOf(".jpeg")>0) || (strFileName.lastIndexOf(".gif")>0) || (strFileName.lastIndexOf(".png")>0) || (strFileName.lastIndexOf(".bmp")>0) ) {
    document.getElementById("REX_MEDIALIST_PREVIEW").src = "../index.php?rex_resize=160a__"+document.getElementById("REX_MEDIA_1").value;
    document.getElementById("REX_MEDIALIST_PREVIEWC").style.display = "block";
  } else {
    document.getElementById("REX_MEDIALIST_PREVIEWC").style.display = "none";
  }
}
function rex_media_hidepreview(){
    document.getElementById("REX_MEDIALIST_PREVIEWC").style.display = "none";
}
addEvent(document.getElementById("REX_MEDIA_1"),"blur",rex_media_hidepreview);
addEvent(document.getElementById("REX_MEDIA_1"),"change",rex_media_preview);
addEvent(document.getElementById("REX_MEDIA_1"),"click",rex_media_preview);
addEvent(document.getElementById("REX_MEDIA_1"),"mouseover",rex_media_preview);
addEvent(document.getElementById("REX_MEDIA_1"),"mouseout",rex_media_preview);
addEvent(document.getElementById("bildblock"),"mouseover",rex_media_preview);
addEvent(document.getElementById("rex-output"),"mouseover",rex_media_preview);
  </script>
```

**Comment by skerbis** [comment]
Bildvorschau geht im aktuellen Stand von Redaxo 5 wieder. Thema hat sich also erledigt.

**Comment by olien** [comment]
Ok. Danke.
"figure" ist eingebaut. teste doch bitte einmal

**Comment by olien** [comment]
ups

**Comment by olien** [comment]
ist wohl erledigt...ansonsten neu öffnen
